In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st
import statsmodels.api as sm

%matplotlib inline

/anaconda/envs/dand/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [20]:
df = pd.read_csv('2016.csv')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5813 entries, 0 to 5812
Data columns (total 5 columns):
Country Name     5810 non-null object
Country Code     5808 non-null object
Series Name      5808 non-null object
Series Code      5808 non-null object
2016 [YR2016]    5808 non-null object
dtypes: object(5)
memory usage: 227.1+ KB

In [22]:
df = df.set_index(['Country Name'])

In [23]:
df = df.drop(['Country Code', 'Series Code'], axis=1)

In [28]:
df = df.dropna()

In [35]:
df = df.rename(index=str, columns={'2016 [YR2016]': '2016'})

In [36]:
df.head()

                                      Series Name                2016
Country Name
Afghanistan   CO2 emissions (kg per PPP $ of GDP)                  ..
Afghanistan                     GDP (current US$)    19469022207.6852
Afghanistan                 GDP growth (annual %)    2.23227175937284
Afghanistan          GDP per capita (current US$)     561.77874627093
Afghanistan      GDP per capita growth (annual %)  -0.480285140074571

In [40]:
df['2016'] = df['2016'].replace('..', 0)

In [42]:
df['2016'] = df['2016'].astype('float')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5808 entries, Afghanistan to Zimbabwe
Data columns (total 2 columns):
Series Name    5808 non-null object
2016           5808 non-null float64
dtypes: float64(1), object(1)
memory usage: 136.1+ KB

In [46]:
df = df.pivot_table(index='Country Name', columns='Series Name', values='2016')

In [47]:
df.head()

Series Name,CO2 emissions (kg per PPP $ of GDP),GDP (current US$),GDP growth (annual %),GDP per capita (current US$),GDP per capita growth (annual %),GDP per unit of energy use (PPP $ per kg of oil equivalent),Labor force with advanced education (% of total working-age population with advanced education),"Labor force with advanced education, female (% of female working-age population with advanced education)","Labor force with advanced education, male (% of male working-age population with advanced education)","Life expectancy at birth, female (years)",...,"Population ages 0-14, male (% of total)",Population ages 15-64 (% of total),Population ages 65 and above (% of total),Population density (people per sq. km of land area),Population growth (annual %),"Population, female (% of total)","Population, male (% of total)","Population, total","Suicide mortality rate (per 100,000 population)",Women's share of population ages 15+ living with HIV (%)
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,1.946902e+10,2.232272,561.778746,-0.480285,0.0,0.0,0.0,0.0,0.0,...,43.658938,53.598917,2.541558,53.083405,2.689163,48.452199,51.547801,34656032.0,0.0,28.627356
Albania,0.0,1.186387e+10,3.369989,4124.982390,3.535389,0.0,0.0,0.0,0.0,0.0,...,18.227566,69.443689,12.833914,104.967190,-0.159880,49.504843,50.495157,2876101.0,0.0,29.800597
Algeria,0.0,1.590491e+11,3.300000,3916.881571,1.431403,0.0,0.0,0.0,0.0,0.0,...,29.307860,64.973928,6.020834,17.048895,1.825463,49.500379,50.499621,40606052.0,0.0,46.194624
American Samoa,0.0,6.580000e+08,-2.619414,11834.745229,-2.728006,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,277.995000,0.111575,0.000000,0.000000,55599.0,0.0,0.000000
Andorra,0.0,2.858518e+09,1.232243,36988.622030,2.192418,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,164.427660,-0.944017,0.000000,0.000000,77281.0,0.0,0.000000

In [54]:
df.to_csv('2016_cleaned.csv')